import test from 'node:test';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';import {promises as fs} from 'node:fs';
import {deliverToCodex,runCodexBridge} from '../lib/codex.mjs';
const project=os.tmpdir(),threadId='thread-fixture',message={messageId:'fixture-message',from:'peer',body:'Please share ownership.'};
function connection(type='idle',cwd=project){const calls=[];return{calls,close(){},async call(method,params){calls.push({method,params});if(method==='thread/read')return{thread:{cwd,status:{type}}};if(method==='thread/turns/list')return{data:[{id:'active-turn',status:'inProgress'}]};return{};}};}
test('idle delivery targets existing thread without model or permission overrides',async()=>{const c=connection();await deliverToCodex(c,{project,threadId,message,agentId:'my-id'});assert.deepEqual(c.calls.map(x=>x.method),['thread/read','turn/start']);const p=c.calls[1].params;assert.equal(p.threadId,threadId);assert.equal(p.clientUserMessageId,message.messageId);assert.ok(p.input[0].text.includes('--as my-id'));assert.deepEqual(Object.keys(p).sort(),['clientUserMessageId','input','threadId']);});
test('busy delivery steers exact active turn without concurrent turn/start',async()=>{const c=connection('active');await deliverToCodex(c,{project,threadId,message});assert.equal(c.calls.at(-1).method,'turn/steer');assert.equal(c.calls.at(-1).params.expectedTurnId,'active-turn');assert.equal(c.calls.filter(x=>x.method==='turn/start').length,0);});
test('project mismatch, unloaded thread and missing active turn refuse submission',async()=>{const c=connection('idle',path.parse(project).root);await assert.rejects(deliverToCodex(c,{project,threadId,message}),/different project/);assert.equal(c.calls.length,1);for(const type of ['notLoaded','systemError']){const x=connection(type);await assert.rejects(deliverToCodex(x,{project,threadId,message}),/no resume/);assert.equal(x.calls.length,1);}const x=connection('active');const original=x.call;x.call=async(m,p)=>m==='thread/turns/list'?{data:[]}:original.call(x,m,p);await assert.rejects(deliverToCodex(x,{project,threadId,message}),/unavailable/);});
test('bridge fences uncertain submission durably and never acknowledges or retries',async()=>{const calls=[],controller=new AbortController(),c=connection();const orig=c.call;c.call=async(m,p)=>{if(m==='turn/start')throw new Error('uncertain');return orig.call(c,m,p);};const options={project,threadId,connection:c,signal:controller.signal,rpcImpl:async(_,fields)=>{calls.push(fields);if(fields.op==='inbox')return{ok:true,messages:[message],cursor:1};return{ok:true};},waitImpl:async()=>{controller.abort();return{ok:true,messages:[message],cursor:1};}};await runCodexBridge(options);assert.equal(calls.filter(x=>x.op==='notified'&&x.adapter==='codex-attempted').length,1);assert.equal(calls.filter(x=>x.op==='notified'&&x.adapter==='codex-accepted').length,0);assert.equal(calls.filter(x=>x.op==='ack').length,0);assert.equal(calls.filter(x=>x.status==='delivery-needs-review').length,1);});
test('persisted attempt marker prevents automatic wake after restart',async()=>{const c=connection(),controller=new AbortController();await runCodexBridge({project,threadId,connection:c,signal:controller.signal,rpcImpl:async(_,f)=>f.op==='inbox'?{ok:true,messages:[{...message,notified:[{agentId:`codex:${threadId}`,adapter:'codex-attempted'}]}],cursor:1}:{ok:true},waitImpl:async()=>{controller.abort();return{ok:true,messages:[],cursor:1};}});assert.equal(c.calls.filter(x=>x.method==='turn/start').length,0);});
test('broker transport reconnect retries only waiting, never a submitted notification',async()=>{const c=connection(),controller=new AbortController();let waits=0;await runCodexBridge({project,threadId,connection:c,signal:controller.signal,rpcImpl:async(_,f)=>f.op==='inbox'?{ok:true,messages:[message],cursor:1}:{ok:true},waitImpl:async()=>{waits++;if(waits===1)throw new Error('broker restarted');controller.abort();return{ok:true,messages:[],cursor:1};}});assert.equal(waits,2);assert.equal(c.calls.filter(x=>x.method==='turn/start').length,1);});
test('duplicate durable admission by another bridge never submits a second wake',async()=>{const c=connection(),controller=new AbortController();await runCodexBridge({project,threadId,connection:c,signal:controller.signal,rpcImpl:async(_,f)=>f.op==='inbox'?{ok:true,messages:[message],cursor:1}:f.op==='notified'?{ok:true,duplicate:true}:{ok:true},waitImpl:async()=>{controller.abort();return{ok:true,messages:[],cursor:1};}});assert.equal(c.calls.filter(x=>['turn/start','turn/steer'].includes(x.method)).length,0);});
